import { Inter } from "next/font/google";
import "./globals.css";
// import {  } from "@/lib/provider";
import StoreProvider from "./StoreProvider";
// import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-mode="dark">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" />
      </head>
      <body className={inter.className}>
        <StoreProvider>
        {children}
        </StoreProvider>
        </body>
    </html>
  );
}
